apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-redis
  namespace: gitlab
  labels:
    app: gitlab-redis
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      app: gitlab-redis
  replicas: 2
  template:
    metadata:
      labels:
        name: gitlab-redis
        app: gitlab-redis
    spec:
      containers:
      - name: gitlab-redis
        image: redis:3.2.4
        ports:
        - name: redis
          containerPort: 6379
        volumeMounts:
        - mountPath: /var/lib/redis
          name: data
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 60
          timeoutSeconds: 30
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 60
          timeoutSeconds: 30
      volumes:
      - name: data
        emptyDir: {}
